[vlive]
title = "(G)I-DLE ─ Star Board"
url = "https://www.vlive.tv/channel/CE2621/board/5013?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[vlive_notice]
title = "(G)I-DLE ─ Notice"
url = "https://www.vlive.tv/channel/CE2621/board/1578"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"